name: Create and Update Secrets Workflow

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: 'Name of the secret'
        required: true
        default: 'sn-kv-scope-nas-drive-id'
      secret_value:
        description: 'Value of the secret'
        required: true
      environment:
        description: 'Environment to use (dev or prod)'
        required: true
        default: 'dev'
  issues:
    types: [opened, edited]

jobs:
  create_or_update_secret:
    if: github.event.label.name == 'secret'
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      SECRET_NAME: ${{ github.event.issue.body | fromJson | selectKeys('secret_name') }}
      SECRET_VALUE: ${{ github.event.issue.body | fromJson | selectKeys('secret_value') }}
      VAULT_NAME: ${{ secrets.VAULT_NAME }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Azure CLI
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Login to Azure
        run: |
          az login --service-principal \
            --username ${{ env.ARM_CLIENT_ID }} \
            --password ${{ secrets['ARM_CLIENT_SECRET_' + github.event.inputs.environment.toUpperCase()] }} \
            --tenant ${{ env.ARM_TENANT_ID }}

      - name: Create or Update Secret
        run: |
          az keyvault secret set \
            --name ${{ env.SECRET_NAME }} \
            --value ${{ env.SECRET_VALUE }} \
            --vault-name ${{ env.VAULT_NAME }}
