name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install az cli
        run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
            # sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
            # curl -s https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
            # AZ_REPO=$(lsb_release -cs)
            # echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
            # sudo apt-get update
            # sudo apt-get install azure-cli
      - name: Login Az
        run: az login --service-principal -u 29305fea-ccce-4dc6-b9ea-4f670909846e -p sYp8Q~ozBsHxAqXgmjJjBYzzRTMUKwk1bIUpvcyZ --tenant ec25f121-f9c4-4650-a39c-47cd1939fe8b
      - name: account show
        run: az account show
      - name: dbs show
        run: echo "url=$(az databricks workspace list --resource-group ngktest --query [0].workspaceUrl)  >> $GITHUB_ENV
      - name: echo
        run:  echo "newurl=${{ env.url }}" 
      # - name: create a job
      #   run: curl --netrc --request POST \
      #        https://"${{ env.url }}"/api/2.0/jobs/create \
      #        --data @job.json \
      #        | jq . 
      - run: echo "🍏 This job's status is ${{ job.status }}."
#az databricks workspace list --query [0].workspaceUrl
#az account set --subscription 4daf5ca9-14c9-431c-b6aa-90ec0451f571